### ISSUE TITLE
macos mojave 10.14.6 不兼容无法运行

### ISSUE THREAD

**Issue by shendanpuff** [HistoryZhang/SpiderCard#1]
macos mojave 10.14.6 不兼容无法运行

**Comment by KelvinQQ** [comment]
试一下这个，这边没有10.14.6的系统，应该是之前的最低版本号没有支持到。

[SprideCard.dmg.zip](https://github.com/HistoryZhang/SpiderCard/files/6920052/SprideCard.dmg.zip)

**Comment by shendanpuff** [comment]
> 试一下这个，这边没有10.14.6的系统，应该是之前的最低版本号没有支持到。
> 
> [SprideCard.dmg.zip](https://github.com/HistoryZhang/SpiderCard/files/6920052/SprideCard.dmg.zip)

好的，我试一下，多谢
